### ISSUE TITLE
What should be ideal Result Type for `DELETE` HTTP Method?

### ISSUE THREAD

**Issue by chinmay-inaza** [codecat15/HttpUtility#25]
Suppose I am sending a request with `DELETE` Http Method. I am getting response code 204 with no data.

What is the best way to handle this? What should be the ideal model for this?

**Comment by chinmay-inaza** [comment]
How can I make `resultType` optional for `DELETE` method?

**Comment by chinmay-inaza** [comment]
Or have a `NullResponse` model which I can pass in such cases?

**Comment by codecat15** [comment]
HTTP status code `204` means `no response` and in general, for delete, it's acceptable for the API to send this response code.

If an API is performing some activity then I strongly feel, it should send a JSON indicating what did it do with the request that was sent

To tackle a blank or empty response you can create a struct with no property and send it to the utility and it'll be fine but in general, I don't recommend this approach at all because an empty struct with no value does not make sense in the code.

I would rather ask the API developer to send a response JSON with the status code.

**Comment by chinmay-inaza** [comment]
When I parse empty data using empty struct conforming to Decodable, I get this error:

```
dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: \"The given data was not valid JSON.\", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 \"Unable to parse empty data.\" UserInfo={NSDebugDescription=Unable to parse empty data.})))
```

This is how my code looks like:

```
do {
          return try decoder.decode(responseType, from: data)
     } catch let error {
          debugPrint("data - \(data)")
          debugPrint("error while decoding JSON response =>\(String(describing: error))")
          throw NetworkError.runtimeError(String(describing: error))
     }
```

**Comment by chinmay-inaza** [comment]
I feel response 204 is a success message which already tells us about success and again sending JSON with it seems a bit redundant. 

Anyway, backend API response is quite not in my control. Thus, I might have to stick to `NullResponse Struct`
